-- Exercise catalog seed — generated from shared/lib/program/exercise-catalog.json
-- via scripts/generate-exercise-seed.mjs; do not edit by hand.
-- Idempotent: re-running updates existing rows in place. Run in the Supabase
-- SQL editor after schema.sql.

insert into public.exercises
  (id, name, muscle, default_kg, is_barbell, is_dumbbell, is_bodyweight,
   is_timed, is_compound, bodyweight_load, sort_order)
values
  ('barbell-bench-press', 'Barbell Bench Press', 'Chest', 60, true, false, false, false, true, null, 0),
  ('incline-dumbbell-press', 'Incline Dumbbell Press', 'Chest', 12, false, true, false, false, true, null, 1),
  ('flat-dumbbell-press', 'Flat Dumbbell Press', 'Chest', 13, false, true, false, false, true, null, 2),
  ('incline-machine-press', 'Incline Machine Press', 'Chest', 40, false, false, false, false, false, null, 3),
  ('cable-chest-fly', 'Cable Chest Fly', 'Chest', 15, false, false, false, false, false, null, 4),
  ('dumbbell-chest-fly', 'Dumbbell Chest Fly', 'Chest', 10, false, true, false, false, false, null, 5),
  ('cable-crossover', 'Cable Crossover', 'Chest', 12, false, false, false, false, false, null, 6),
  ('pec-deck', 'Pec Deck', 'Chest', 40, false, false, false, false, false, null, 7),
  ('decline-barbell-bench-press', 'Decline Barbell Bench Press', 'Chest', 60, true, false, false, false, true, null, 8),
  ('push-ups', 'Push-ups', 'Chest', 0, false, false, false, false, false, 0.64, 9),
  ('seated-shoulder-press', 'Seated Shoulder Press', 'Front delts', 11, false, true, false, false, false, null, 10),
  ('overhead-barbell-press', 'Overhead Barbell Press', 'Front delts', 40, true, false, false, false, true, null, 11),
  ('dumbbell-shoulder-press', 'Dumbbell Shoulder Press', 'Front delts', 12, false, true, false, false, false, null, 12),
  ('arnold-press', 'Arnold Press', 'Front delts', 10, false, true, false, false, false, null, 13),
  ('front-raise', 'Front Raise', 'Front delts', 6, false, true, false, false, false, null, 14),
  ('lateral-raises', 'Lateral Raises', 'Side delts', 5, false, true, false, false, false, null, 15),
  ('cable-lateral-raise', 'Cable Lateral Raise', 'Side delts', 9, false, false, false, false, false, null, 16),
  ('machine-lateral-raise', 'Machine Lateral Raise', 'Side delts', 25, false, false, false, false, false, null, 17),
  ('upright-row', 'Upright Row', 'Side delts', 30, false, false, false, false, false, null, 18),
  ('rear-delt-fly', 'Rear Delt Fly', 'Rear delts', 6, false, true, false, false, false, null, 19),
  ('reverse-fly', 'Reverse Fly', 'Rear delts', 12, false, false, false, false, false, null, 20),
  ('face-pulls', 'Face Pulls', 'Rear delts', 25, false, false, false, false, false, null, 21),
  ('tricep-rope-pushdown', 'Tricep Rope Pushdown', 'Triceps', 30, false, false, false, false, false, null, 22),
  ('overhead-tricep-extension', 'Overhead Tricep Extension', 'Triceps', 22, false, false, false, false, false, null, 23),
  ('close-grip-bench-press', 'Close-Grip Bench Press', 'Triceps', 50, true, false, false, false, true, null, 24),
  ('skull-crushers', 'Skull Crushers', 'Triceps', 25, false, false, false, false, false, null, 25),
  ('tricep-dips', 'Tricep Dips', 'Triceps', 0, false, false, false, false, false, 1, 26),
  ('tricep-kickback', 'Tricep Kickback', 'Triceps', 6, false, true, false, false, false, null, 27),
  ('single-arm-pushdown', 'Single-Arm Pushdown', 'Triceps', 10, false, false, false, false, false, null, 28),
  ('deadlift', 'Deadlift', 'Back', 100, true, false, false, false, true, null, 29),
  ('pull-ups', 'Pull-ups', 'Back', 0, false, false, false, false, true, 1, 30),
  ('barbell-row', 'Barbell Row', 'Back', 60, true, false, false, false, true, null, 31),
  ('lat-pulldown', 'Lat Pulldown', 'Back', 50, false, false, false, false, false, null, 32),
  ('wide-grip-lat-pulldown', 'Wide-Grip Lat Pulldown', 'Back', 50, false, false, false, false, false, null, 33),
  ('seated-cable-row', 'Seated Cable Row', 'Back', 50, false, false, false, false, false, null, 34),
  ('chest-supported-row', 'Chest-Supported Row', 'Back', 20, false, true, false, false, true, null, 35),
  ('single-arm-cable-row', 'Single-Arm Cable Row', 'Back', 22, false, false, false, false, false, null, 36),
  ('t-bar-row', 'T-Bar Row', 'Back', 40, false, false, false, false, true, null, 37),
  ('dumbbell-row', 'Dumbbell Row', 'Back', 22, false, true, false, false, true, null, 38),
  ('straight-arm-pulldown', 'Straight-Arm Pulldown', 'Back', 25, false, false, false, false, false, null, 39),
  ('close-grip-lat-pulldown', 'Close-Grip Lat Pulldown', 'Back', 50, false, false, false, false, false, null, 40),
  ('inverted-row', 'Inverted Row', 'Back', 0, false, false, false, false, false, 0.6, 41),
  ('ez-bar-curl', 'EZ-Bar Curl', 'Biceps', 30, false, false, false, false, false, null, 42),
  ('hammer-curl', 'Hammer Curl', 'Biceps', 7, false, true, false, false, false, null, 43),
  ('incline-dumbbell-curl', 'Incline Dumbbell Curl', 'Biceps', 7, false, true, false, false, false, null, 44),
  ('preacher-curl', 'Preacher Curl', 'Biceps', 30, false, false, false, false, false, null, 45),
  ('barbell-curl', 'Barbell Curl', 'Biceps', 30, true, false, false, false, false, null, 46),
  ('cable-curl', 'Cable Curl', 'Biceps', 25, false, false, false, false, false, null, 47),
  ('concentration-curl', 'Concentration Curl', 'Biceps', 8, false, true, false, false, false, null, 48),
  ('barbell-back-squat', 'Barbell Back Squat', 'Quads', 80, true, false, false, false, true, null, 49),
  ('leg-press', 'Leg Press', 'Quads', 120, false, false, false, false, true, null, 50),
  ('walking-lunges', 'Walking Lunges', 'Quads', 10, false, true, false, false, false, null, 51),
  ('front-squat', 'Front Squat', 'Quads', 60, true, false, false, false, true, null, 52),
  ('hack-squat', 'Hack Squat', 'Quads', 60, false, false, false, false, true, null, 53),
  ('leg-extension', 'Leg Extension', 'Quads', 40, false, false, false, false, false, null, 54),
  ('bulgarian-split-squat', 'Bulgarian Split Squat', 'Quads', 10, false, true, false, false, false, null, 55),
  ('goblet-squat', 'Goblet Squat', 'Quads', 20, false, false, false, false, false, null, 56),
  ('romanian-deadlift', 'Romanian Deadlift', 'Hamstrings', 70, true, false, false, false, true, null, 57),
  ('leg-curl', 'Leg Curl', 'Hamstrings', 45, false, false, false, false, false, null, 58),
  ('seated-leg-curl', 'Seated Leg Curl', 'Hamstrings', 45, false, false, false, false, false, null, 59),
  ('good-morning', 'Good Morning', 'Hamstrings', 40, true, false, false, false, false, null, 60),
  ('hip-thrust', 'Hip Thrust', 'Hamstrings', 60, true, false, false, false, true, null, 61),
  ('standing-calf-raise', 'Standing Calf Raise', 'Calves', 60, false, false, false, false, false, null, 62),
  ('seated-calf-raise', 'Seated Calf Raise', 'Calves', 40, false, false, false, false, false, null, 63),
  ('hanging-leg-raise', 'Hanging Leg Raise', 'Core', 0, false, false, true, false, false, 0.5, 64),
  ('hanging-knee-raise', 'Hanging Knee Raise', 'Core', 0, false, false, true, false, false, 0.4, 65),
  ('toes-to-bar', 'Toes to Bar', 'Core', 0, false, false, true, false, false, 0.55, 66),
  ('lying-leg-raise', 'Lying Leg Raise', 'Core', 0, false, false, true, false, false, 0.4, 67),
  ('reverse-crunch', 'Reverse Crunch', 'Core', 0, false, false, true, false, false, 0.3, 68),
  ('crunch', 'Crunch', 'Core', 0, false, false, true, false, false, 0.25, 69),
  ('sit-up', 'Sit-up', 'Core', 0, false, false, true, false, false, 0.4, 70),
  ('decline-sit-up', 'Decline Sit-up', 'Core', 0, false, false, true, false, false, 0.5, 71),
  ('bicycle-crunch', 'Bicycle Crunch', 'Core', 0, false, false, true, false, false, 0.3, 72),
  ('v-up', 'V-Up', 'Core', 0, false, false, true, false, false, 0.45, 73),
  ('dead-bug', 'Dead Bug', 'Core', 0, false, false, true, false, false, 0.2, 74),
  ('ab-wheel-rollout', 'Ab Wheel Rollout', 'Core', 0, false, false, true, false, false, 0.5, 75),
  ('cable-crunch', 'Cable Crunch', 'Core', 30, false, false, false, false, false, null, 76),
  ('machine-crunch', 'Machine Crunch', 'Core', 45, false, false, false, false, false, null, 77),
  ('russian-twist', 'Russian Twist', 'Core', 5, false, false, false, false, false, null, 78),
  ('cable-woodchopper', 'Cable Woodchopper', 'Core', 20, false, false, false, false, false, null, 79),
  ('landmine-twist', 'Landmine Twist', 'Core', 20, false, false, false, false, false, null, 80),
  ('pallof-press', 'Pallof Press', 'Core', 15, false, false, false, false, false, null, 81),
  ('plank', 'Plank', 'Core', 0, false, false, true, true, false, null, 82),
  ('side-plank', 'Side Plank', 'Core', 0, false, false, true, true, false, null, 83),
  ('hollow-hold', 'Hollow Hold', 'Core', 0, false, false, true, true, false, null, 84),
  ('flutter-kicks', 'Flutter Kicks', 'Core', 0, false, false, true, true, false, null, 85),
  ('mountain-climbers', 'Mountain Climbers', 'Core', 0, false, false, true, true, false, null, 86),
  ('incline-barbell-bench-press', 'Incline Barbell Bench Press', 'Chest', 50, true, false, false, false, true, null, 87),
  ('machine-chest-press', 'Machine Chest Press', 'Chest', 40, false, false, false, false, false, null, 88),
  ('smith-machine-bench-press', 'Smith Machine Bench Press', 'Chest', 40, false, false, false, false, false, null, 89),
  ('cable-bench-press', 'Cable Bench Press', 'Chest', 25, false, false, false, false, false, null, 90),
  ('incline-cable-fly', 'Incline Cable Fly', 'Chest', 12, false, false, false, false, false, null, 91),
  ('decline-cable-fly', 'Decline Cable Fly', 'Chest', 12, false, false, false, false, false, null, 92),
  ('dumbbell-pullover', 'Dumbbell Pullover', 'Chest', 16, false, false, false, false, false, null, 93),
  ('chest-dip', 'Chest Dip', 'Chest', 0, false, false, true, false, false, 1, 94),
  ('decline-push-up', 'Decline Push-up', 'Chest', 0, false, false, true, false, false, 0.7, 95),
  ('svend-press', 'Svend Press', 'Chest', 5, false, false, false, false, false, null, 96),
  ('machine-shoulder-press', 'Machine Shoulder Press', 'Front delts', 30, false, false, false, false, false, null, 97),
  ('cable-shoulder-press', 'Cable Shoulder Press', 'Front delts', 20, false, false, false, false, false, null, 98),
  ('plate-front-raise', 'Plate Front Raise', 'Front delts', 10, false, false, false, false, false, null, 99),
  ('cable-front-raise', 'Cable Front Raise', 'Front delts', 9, false, false, false, false, false, null, 100),
  ('landmine-press', 'Landmine Press', 'Front delts', 20, false, false, false, false, false, null, 101),
  ('push-press', 'Push Press', 'Front delts', 40, true, false, false, false, true, null, 102),
  ('z-press', 'Z Press', 'Front delts', 30, true, false, false, false, false, null, 103),
  ('dumbbell-upright-row', 'Dumbbell Upright Row', 'Side delts', 10, false, true, false, false, false, null, 104),
  ('cable-upright-row', 'Cable Upright Row', 'Side delts', 25, false, false, false, false, false, null, 105),
  ('single-arm-cable-lateral-raise', 'Single-Arm Cable Lateral Raise', 'Side delts', 7, false, false, false, false, false, null, 106),
  ('lying-dumbbell-lateral-raise', 'Lying Dumbbell Lateral Raise', 'Side delts', 5, false, false, false, false, false, null, 107),
  ('cable-rear-delt-fly', 'Cable Rear Delt Fly', 'Rear delts', 9, false, false, false, false, false, null, 108),
  ('reverse-pec-deck', 'Reverse Pec Deck', 'Rear delts', 35, false, false, false, false, false, null, 109),
  ('dumbbell-rear-delt-row', 'Dumbbell Rear Delt Row', 'Rear delts', 12, false, true, false, false, false, null, 110),
  ('cable-overhead-tricep-extension', 'Cable Overhead Tricep Extension', 'Triceps', 25, false, false, false, false, false, null, 111),
  ('straight-bar-pushdown', 'Straight-Bar Pushdown', 'Triceps', 30, false, false, false, false, false, null, 112),
  ('reverse-grip-pushdown', 'Reverse-Grip Pushdown', 'Triceps', 20, false, false, false, false, false, null, 113),
  ('diamond-push-up', 'Diamond Push-up', 'Triceps', 0, false, false, true, false, false, 0.64, 114),
  ('bench-dip', 'Bench Dip', 'Triceps', 0, false, false, true, false, false, 0.6, 115),
  ('machine-tricep-extension', 'Machine Tricep Extension', 'Triceps', 35, false, false, false, false, false, null, 116),
  ('tate-press', 'Tate Press', 'Triceps', 10, false, true, false, false, false, null, 117),
  ('barbell-jm-press', 'Barbell JM Press', 'Triceps', 40, true, false, false, false, false, null, 118),
  ('pendlay-row', 'Pendlay Row', 'Back', 60, true, false, false, false, true, null, 119),
  ('meadows-row', 'Meadows Row', 'Back', 25, false, false, false, false, false, null, 120),
  ('landmine-row', 'Landmine Row', 'Back', 30, false, false, false, false, false, null, 121),
  ('neutral-grip-lat-pulldown', 'Neutral-Grip Lat Pulldown', 'Back', 50, false, false, false, false, false, null, 122),
  ('reverse-grip-lat-pulldown', 'Reverse-Grip Lat Pulldown', 'Back', 45, false, false, false, false, false, null, 123),
  ('chin-ups', 'Chin-ups', 'Back', 0, false, false, true, false, true, 1, 124),
  ('barbell-seal-row', 'Barbell Seal Row', 'Back', 50, true, false, false, false, true, null, 125),
  ('rack-pull', 'Rack Pull', 'Back', 100, true, false, false, false, true, null, 126),
  ('smith-machine-row', 'Smith Machine Row', 'Back', 40, false, false, false, false, true, null, 127),
  ('yates-row', 'Yates Row', 'Back', 50, true, false, false, false, true, null, 128),
  ('dumbbell-bicep-curl', 'Dumbbell Bicep Curl', 'Biceps', 10, false, true, false, false, false, null, 129),
  ('spider-curl', 'Spider Curl', 'Biceps', 8, false, true, false, false, false, null, 130),
  ('ez-bar-reverse-curl', 'EZ-Bar Reverse Curl', 'Biceps', 20, false, false, false, false, false, null, 131),
  ('drag-curl', 'Drag Curl', 'Biceps', 30, true, false, false, false, false, null, 132),
  ('rope-hammer-curl', 'Rope Hammer Curl', 'Biceps', 25, false, false, false, false, false, null, 133),
  ('bayesian-curl', 'Bayesian Curl', 'Biceps', 9, false, false, false, false, false, null, 134),
  ('zottman-curl', 'Zottman Curl', 'Biceps', 9, false, true, false, false, false, null, 135),
  ('wide-grip-barbell-curl', 'Wide-Grip Barbell Curl', 'Biceps', 30, true, false, false, false, false, null, 136),
  ('dumbbell-lunge', 'Dumbbell Lunge', 'Quads', 12, false, true, false, false, false, null, 137),
  ('reverse-lunge', 'Reverse Lunge', 'Quads', 12, false, true, false, false, false, null, 138),
  ('dumbbell-step-up', 'Dumbbell Step-up', 'Quads', 12, false, true, false, false, false, null, 139),
  ('sissy-squat', 'Sissy Squat', 'Quads', 0, false, false, true, false, false, 0.7, 140),
  ('smith-machine-squat', 'Smith Machine Squat', 'Quads', 40, false, false, false, false, true, null, 141),
  ('zercher-squat', 'Zercher Squat', 'Quads', 50, true, false, false, false, true, null, 142),
  ('v-squat', 'V-Squat', 'Quads', 60, false, false, false, false, true, null, 143),
  ('box-squat', 'Box Squat', 'Quads', 60, true, false, false, false, true, null, 144),
  ('cossack-squat', 'Cossack Squat', 'Quads', 0, false, false, true, false, false, 0.65, 145),
  ('pistol-squat', 'Pistol Squat', 'Quads', 0, false, false, true, false, true, 0.9, 146),
  ('stiff-leg-deadlift', 'Stiff-Leg Deadlift', 'Hamstrings', 60, true, false, false, false, true, null, 147),
  ('dumbbell-romanian-deadlift', 'Dumbbell Romanian Deadlift', 'Hamstrings', 20, false, true, false, false, true, null, 148),
  ('glute-bridge', 'Glute Bridge', 'Hamstrings', 0, false, false, true, false, false, 0.5, 149),
  ('single-leg-hip-thrust', 'Single-Leg Hip Thrust', 'Hamstrings', 0, false, false, true, false, false, 0.5, 150),
  ('cable-pull-through', 'Cable Pull-Through', 'Hamstrings', 25, false, false, false, false, false, null, 151),
  ('nordic-curl', 'Nordic Curl', 'Hamstrings', 0, false, false, true, false, false, 0.9, 152),
  ('kettlebell-swing', 'Kettlebell Swing', 'Hamstrings', 16, false, false, false, false, false, null, 153),
  ('frog-pump', 'Frog Pump', 'Hamstrings', 0, false, false, true, false, false, 0.4, 154),
  ('leg-press-calf-raise', 'Leg Press Calf Raise', 'Calves', 80, false, false, false, false, false, null, 155),
  ('single-leg-calf-raise', 'Single-Leg Calf Raise', 'Calves', 10, false, false, false, false, false, null, 156),
  ('donkey-calf-raise', 'Donkey Calf Raise', 'Calves', 60, false, false, false, false, false, null, 157),
  ('smith-machine-calf-raise', 'Smith Machine Calf Raise', 'Calves', 40, false, false, false, false, false, null, 158),
  ('captains-chair-leg-raise', 'Captain''s Chair Leg Raise', 'Core', 0, false, false, true, false, false, 0.5, 159),
  ('dragon-flag', 'Dragon Flag', 'Core', 0, false, false, true, false, false, 0.6, 160),
  ('dumbbell-side-bend', 'Dumbbell Side Bend', 'Core', 12, false, false, false, false, false, null, 161),
  ('windshield-wipers', 'Windshield Wipers', 'Core', 0, false, false, true, false, false, 0.5, 162),
  ('bird-dog', 'Bird Dog', 'Core', 0, false, false, true, false, false, 0.15, 163),
  ('scissor-kicks', 'Scissor Kicks', 'Core', 0, false, false, true, false, false, 0.3, 164),
  ('side-crunch', 'Side Crunch', 'Core', 0, false, false, true, false, false, 0.25, 165),
  ('plank-jack', 'Plank Jack', 'Core', 0, false, false, true, true, false, null, 166),
  ('back-extension', 'Back Extension', 'Core', 0, false, false, true, false, false, 0.4, 167),
  ('burpees', 'Burpees', 'Full body', 0, false, false, true, false, false, 0.6, 168),
  ('battle-ropes', 'Battle Ropes', 'Full body', 0, false, false, true, true, false, null, 169),
  ('farmers-walk', 'Farmer''s Walk', 'Full body', 24, false, true, false, true, false, null, 170),
  ('clean-and-press', 'Clean and Press', 'Full body', 40, true, false, false, false, true, null, 171),
  ('box-jump', 'Box Jump', 'Full body', 0, false, false, true, false, false, 0.6, 172),
  ('jump-rope', 'Jump Rope', 'Full body', 0, false, false, true, true, false, null, 173),
  ('bear-crawl', 'Bear Crawl', 'Full body', 0, false, false, true, true, false, null, 174)
on conflict (id) do update set
  name = excluded.name,
  muscle = excluded.muscle,
  default_kg = excluded.default_kg,
  is_barbell = excluded.is_barbell,
  is_dumbbell = excluded.is_dumbbell,
  is_bodyweight = excluded.is_bodyweight,
  is_timed = excluded.is_timed,
  is_compound = excluded.is_compound,
  bodyweight_load = excluded.bodyweight_load,
  sort_order = excluded.sort_order,
  updated_at = now();
