import type {
  DayKey,
  DayTemplate,
  ExerciseInstance,
  ScheduledDay,
} from "@/shared/types";

import { muscleOf } from "./exercises";

// Template exercises use the name as id; live sessions re-id via makeExercise
const ex = (name: string, sets: number, reps: string): ExerciseInstance => ({
  id: name,
  name,
  sets,
  reps,
  target: reps,
  muscle: muscleOf(name),
});

export const DAY: Record<DayKey, DayTemplate> = {
  pushA: {
    key: "pushA",
    name: "Push A",
    sub: "Chest-focused",
    dur: 65,
    muscles: ["Chest", "Front delts", "Side delts", "Triceps"],
    exercises: [
      ex("Barbell Bench Press", 4, "6–8"),
      ex("Incline Dumbbell Press", 3, "8–10"),
      ex("Seated Shoulder Press", 3, "8–10"),
      ex("Lateral Raises", 4, "12–15"),
      ex("Cable Chest Fly", 3, "12"),
      ex("Tricep Rope Pushdown", 3, "10–12"),
      ex("Overhead Tricep Extension", 3, "10–12"),
    ],
  },
  pullA: {
    key: "pullA",
    name: "Pull A",
    sub: "Back-focused",
    dur: 65,
    muscles: ["Back", "Rear delts", "Biceps"],
    exercises: [
      ex("Deadlift", 3, "4–6"),
      ex("Pull-ups", 4, "6–10"),
      ex("Barbell Row", 4, "6–8"),
      ex("Lat Pulldown", 3, "10–12"),
      ex("Seated Cable Row", 3, "10–12"),
      ex("Face Pulls", 3, "15"),
      ex("EZ-Bar Curl", 3, "8–10"),
      ex("Hammer Curl", 3, "10–12"),
    ],
  },
  legs: {
    key: "legs",
    name: "Leg Day",
    sub: "Quads & hamstrings",
    dur: 60,
    muscles: ["Quads", "Hamstrings", "Calves", "Core"],
    exercises: [
      ex("Barbell Back Squat", 4, "6–8"),
      ex("Leg Press", 3, "10–12"),
      ex("Walking Lunges", 3, "10 ea"),
      ex("Romanian Deadlift", 3, "8–10"),
      ex("Leg Curl", 3, "12"),
      ex("Standing Calf Raise", 4, "12–15"),
      ex("Hanging Leg Raise", 3, "12–15"),
    ],
  },
  pushB: {
    key: "pushB",
    name: "Push B",
    sub: "Shoulder-focused",
    dur: 60,
    muscles: ["Front delts", "Chest", "Side delts", "Triceps"],
    exercises: [
      ex("Overhead Barbell Press", 4, "6–8"),
      ex("Flat Dumbbell Press", 3, "8–10"),
      ex("Incline Machine Press", 3, "10"),
      ex("Cable Lateral Raise", 4, "12–15"),
      ex("Rear Delt Fly", 3, "15"),
      ex("Close-Grip Bench Press", 3, "8–10"),
    ],
  },
  pullB: {
    key: "pullB",
    name: "Pull B",
    sub: "Arm & width-focused",
    dur: 55,
    muscles: ["Back", "Rear delts", "Biceps"],
    exercises: [
      ex("Chest-Supported Row", 3, "8–10"),
      ex("Wide-Grip Lat Pulldown", 3, "10–12"),
      ex("Single-Arm Cable Row", 3, "10 ea"),
      ex("Reverse Fly", 3, "15"),
      ex("Incline Dumbbell Curl", 3, "10"),
      ex("Preacher Curl", 3, "10–12"),
    ],
  },
  upper: {
    key: "upper",
    name: "Upper body",
    sub: "Chest, back & arms",
    dur: 60,
    muscles: ["Chest", "Back", "Front delts", "Biceps"],
    exercises: [
      ex("Barbell Bench Press", 4, "6–8"),
      ex("Barbell Row", 4, "6–8"),
      ex("Overhead Barbell Press", 3, "8–10"),
      ex("Lat Pulldown", 3, "10–12"),
      ex("EZ-Bar Curl", 3, "8–10"),
      ex("Tricep Rope Pushdown", 3, "10–12"),
    ],
  },
  lower: {
    key: "lower",
    name: "Lower body",
    sub: "Legs & core",
    dur: 55,
    muscles: ["Quads", "Hamstrings", "Calves"],
    exercises: [
      ex("Barbell Back Squat", 4, "6–8"),
      ex("Leg Press", 3, "10–12"),
      ex("Walking Lunges", 3, "10 ea"),
      ex("Romanian Deadlift", 3, "8–10"),
      ex("Leg Curl", 3, "12"),
      ex("Standing Calf Raise", 4, "12–15"),
    ],
  },
  full: {
    key: "full",
    name: "Full Body",
    sub: "Everything, every session",
    dur: 50,
    muscles: ["Quads", "Chest", "Back", "Front delts"],
    exercises: [
      ex("Barbell Back Squat", 3, "6–8"),
      ex("Barbell Bench Press", 3, "8–10"),
      ex("Barbell Row", 3, "8–10"),
      ex("Overhead Barbell Press", 2, "10"),
      ex("EZ-Bar Curl", 2, "10–12"),
    ],
  },
  chest: {
    key: "chest",
    name: "Chest",
    sub: "Chest day",
    dur: 55,
    muscles: ["Chest", "Front delts", "Triceps"],
    exercises: [
      ex("Barbell Bench Press", 4, "6–8"),
      ex("Incline Dumbbell Press", 3, "8–10"),
      ex("Flat Dumbbell Press", 3, "8–10"),
      ex("Cable Chest Fly", 3, "12"),
      ex("Close-Grip Bench Press", 3, "8–10"),
    ],
  },
  back: {
    key: "back",
    name: "Back",
    sub: "Back day",
    dur: 55,
    muscles: ["Back", "Rear delts"],
    exercises: [
      ex("Deadlift", 3, "4–6"),
      ex("Pull-ups", 4, "6–10"),
      ex("Barbell Row", 4, "6–8"),
      ex("Lat Pulldown", 3, "10–12"),
      ex("Seated Cable Row", 3, "10–12"),
      ex("Face Pulls", 3, "15"),
    ],
  },
  shoulders: {
    key: "shoulders",
    name: "Shoulders",
    sub: "Shoulder day",
    dur: 50,
    muscles: ["Front delts", "Side delts", "Rear delts"],
    exercises: [
      ex("Overhead Barbell Press", 4, "6–8"),
      ex("Seated Shoulder Press", 3, "8–10"),
      ex("Lateral Raises", 4, "12–15"),
      ex("Cable Lateral Raise", 3, "12–15"),
      ex("Rear Delt Fly", 3, "15"),
    ],
  },
  arms: {
    key: "arms",
    name: "Arms",
    sub: "Biceps & triceps",
    dur: 45,
    muscles: ["Biceps", "Triceps"],
    exercises: [
      ex("EZ-Bar Curl", 3, "8–10"),
      ex("Incline Dumbbell Curl", 3, "10"),
      ex("Preacher Curl", 3, "10–12"),
      ex("Tricep Rope Pushdown", 3, "10–12"),
      ex("Overhead Tricep Extension", 3, "10–12"),
      ex("Hammer Curl", 3, "10–12"),
    ],
  },
};

export const dayOf = (key: DayKey, label: string): ScheduledDay => ({
  ...DAY[key],
  exercises: DAY[key].exercises.map((exercise) => ({ ...exercise })),
  label,
});
