// Step-by-step how-to for every exercise in the library.
// Technique sourced from ACE Fitness exercise library, NASM exercise
// library, NSCA Exercise Technique Manual (Kinetic Select), ExRx.net,
// and Schoenfeld (2010) squat kinematics, J Strength Cond Res.
export const STEPS: Record<string, string[]> = {
  // Chest
  "Barbell Bench Press": [
    "Lie on the bench with your feet flat on the floor",
    "Grab the bar a bit wider than your shoulders",
    "Pull your shoulder blades back and down into the bench",
    "Lower the bar slowly until it almost touches your mid chest",
    "Push the bar back up until your arms are straight",
    "Never bounce the bar off your chest, use a spotter when going heavy",
  ],
  "Incline Dumbbell Press": [
    "Set the bench to about 45 degrees and sit back with a dumbbell in each hand",
    "Plant your feet and pull your shoulders back into the bench",
    "Press the dumbbells up over your upper chest until your arms are straight",
    "Lower them slowly toward your upper chest, slightly out to the sides",
    "Press back up while keeping your wrists straight over your elbows",
    "Keep your lower back from over arching",
  ],
  "Flat Dumbbell Press": [
    "Lie on a flat bench with a dumbbell in each hand, feet on the floor",
    "Pull your shoulders back and down into the bench",
    "Start with the dumbbells over your chest, arms straight, palms forward",
    "Lower the dumbbells slowly to the sides of your chest",
    "Press them back up until your arms are straight",
    "Keep your head, shoulders and hips on the bench the whole time",
  ],
  "Incline Machine Press": [
    "Adjust the seat so the handles line up with your upper chest",
    "Sit with your back flat against the pad and feet planted",
    "Pull your shoulders back and down and brace your core",
    "Push the handles away until your arms are nearly straight",
    "Let the handles come back slowly, never let the weights crash down",
    "Keep your shoulder blades against the pad through the whole push",
  ],
  "Cable Chest Fly": [
    "Set both pulleys at about shoulder height and grab a handle in each hand",
    "Step forward with arms out to your sides and a small bend in your elbows",
    "Stand tall with one foot in front for balance",
    "Bring your hands together in front of your chest in a hugging motion",
    "Open your arms back out slowly, stopping in line with your shoulders",
    "Keep that small elbow bend the whole time, never let your arms swing behind you",
  ],

  // Shoulders
  "Seated Shoulder Press": [
    "Sit on a bench with back support, dumbbells held at shoulder height",
    "Keep your head, shoulders and hips against the bench, feet flat",
    "Press the weights straight up until your arms are fully straight",
    "Lower them slowly back to shoulder height",
    "Keep your core tight so your lower back does not arch",
  ],
  "Overhead Barbell Press": [
    "Take the bar from the rack so it rests at the front of your shoulders",
    "Stand tall with feet shoulder width apart and your core tight",
    "Press the bar straight up past your face until your arms are straight overhead",
    "Move your head back slightly so the bar clears your chin",
    "Lower the bar slowly back to your shoulders",
    "Do not lean back at the waist as you press",
  ],
  "Lateral Raises": [
    "Stand tall with a dumbbell in each hand at your sides",
    "Keep a small bend in your elbows and your core tight",
    "Raise both arms out to the sides, elbows and hands rising together",
    "Stop when your arms are level with your shoulders",
    "Lower the weights slowly back to your sides",
    "Do not swing the weights or shrug your shoulders up",
  ],
  "Cable Lateral Raise": [
    "Set the pulley at about waist height with a single handle",
    "Stand side on to the machine and hold the handle with your far hand",
    "Stand tall with your chest up",
    "Lift your arm out to the side until it is level with your shoulder, pause",
    "Lower your arm slowly, then switch sides after your set",
    "Do not lean away from the machine to heave the weight up",
  ],
  "Rear Delt Fly": [
    "Set a bench to about 45 degrees and sit facing the back rest",
    "Rest your chest on the pad, arms hanging down with a small elbow bend",
    "Raise both arms out and up until they reach shoulder height",
    "Squeeze your shoulder blades together at the top",
    "Lower the weights slowly back down",
    "Keep your chest on the pad the whole time",
  ],
  "Reverse Fly": [
    "Set two pulleys at shoulder height, one on each side of you",
    "Grab the right handle with your left hand and the left with your right, arms crossed",
    "Stand tall with your back straight",
    "Pull both arms apart and out to the sides until they form a straight line",
    "Pause, then return slowly to the crossed start",
    "Do not round forward or jerk the weight",
  ],
  "Face Pulls": [
    "Attach a rope to a high pulley and grab it with palms facing down",
    "Step back until your arms are straight with tension on the cable",
    "Stand with knees slightly bent, head and chest tall",
    "Start by squeezing your shoulder blades together, then pull the rope toward your face",
    "Let your elbows go wide and your knuckles turn up as the rope nears your face",
    "Return slowly and keep your body still, no leaning back",
  ],

  // Triceps
  "Tricep Rope Pushdown": [
    "Face the cable machine with a rope set above head height",
    "Grab the rope with both hands, feet hip width apart",
    "Tuck your elbows to your sides and pull your shoulders back and down",
    "Push the rope down until your arms are straight",
    "Let your hands rise slowly until your elbows reach a right angle",
    "Keep your elbows pinned to your sides the whole set",
  ],
  "Overhead Tricep Extension": [
    "Sit or stand tall holding one dumbbell with both hands above your head",
    "Keep your upper arms close to your ears and pointing straight up",
    "Bend your elbows to lower the weight slowly behind your head",
    "Stop when your elbows reach a right angle",
    "Straighten your arms to press the weight back up",
    "Only your forearms move, keep your upper arms still",
  ],
  "Close-Grip Bench Press": [
    "Lie on a flat bench with your feet flat on the floor",
    "Grip the bar slightly narrower than your shoulders",
    "Pull your shoulder blades back and brace your core",
    "Lower the bar slowly to your lower chest, elbows close to your body",
    "Push the bar back up until your arms are straight",
    "Do not let the bar drift away from your body",
  ],

  // Back
  Deadlift: [
    "Stand with feet shoulder width apart, shins almost touching the bar",
    "Push your hips back, keep your back straight and grab the bar",
    "Press your feet into the floor and push your hips forward to stand tall",
    "Keep the bar close to your body the whole way up",
    "Lower the bar by pushing your hips back and bending your knees",
    "You should feel this in your glutes and hamstrings, never your lower back",
  ],
  "Pull-ups": [
    "Grab the bar with palms facing away, thumbs wrapped around it",
    "Hang with arms straight and tighten your core",
    "Pull your shoulders back and down before you start",
    "Pull yourself up by driving your elbows down toward the floor",
    "Stop when your chin reaches the bar, then lower slowly to straight arms",
    "Keep it slow and controlled to protect your shoulders",
  ],
  "Barbell Row": [
    "Hold the bar with palms facing down, hands in line with your shoulders",
    "Bend forward at the hips with a slight knee bend, back straight",
    "Let your arms hang straight down",
    "Pull the bar up toward your belly button",
    "Lower the bar slowly until your arms are straight",
    "Never let your back round, keep it flat to protect your spine",
  ],
  "Lat Pulldown": [
    "Sit at the machine with the thigh pad holding your legs down firmly",
    "Grab the bar and pull your shoulders back and down",
    "Lean back just a little and tighten your core",
    "Pull the bar down to the top of your chest, driving your elbows down",
    "Let the bar rise slowly until your arms are straight overhead",
    "Do not arch your lower back or lean back more than a little",
  ],
  "Wide-Grip Lat Pulldown": [
    "Grab the bar with hands wider than your shoulders",
    "Sit down with your thighs snug under the leg pads",
    "Pull the bar down to your upper chest, keeping your chest up",
    "Let the bar back up slowly until your arms are fully stretched",
    "Do not grip too wide, it cuts the movement short and strains your shoulders",
  ],
  "Seated Cable Row": [
    "Sit with feet planted, knees bent and back straight",
    "Hold the handle with both hands, arms stretched out",
    "Lift your chest and pull your elbows back close to your ribs",
    "Pause for a second when the handle touches your stomach",
    "Straighten your arms slowly to return the weight",
    "Keep your back straight, never jerk the weight",
  ],
  "Chest-Supported Row": [
    "Sit on the machine and rest your chest firmly against the pad",
    "Grab the handles with your arms stretched forward",
    "Pull the handles back until your elbows pass behind your body",
    "Squeeze your shoulder blades together as you pull",
    "Let your arms straighten slowly until your shoulders stretch forward",
    "Keep your chest on the pad the whole time",
  ],
  "Single-Arm Cable Row": [
    "Sit at the cable machine and grab the handle with one hand",
    "Sit with hips back, knees slightly bent and the working arm stretched forward",
    "Pull the handle to the side of your body",
    "Draw your shoulder back and push your chest forward as you pull",
    "Let the arm straighten slowly, then switch arms",
    "Keep your lower back still, let your arm and upper back do the work",
  ],

  // Biceps
  "EZ-Bar Curl": [
    "Stand tall holding the curved bar with palms facing up",
    "Keep your hands about shoulder width apart",
    "Pin your elbows to your sides",
    "Curl the bar up until your forearms point straight up",
    "Lower the bar slowly until your arms are fully straight",
    "Do not swing your body or push your elbows forward to lift",
  ],
  "Hammer Curl": [
    "Stand with a dumbbell in each hand at your sides, palms facing your body",
    "Put one foot slightly in front and tighten your core",
    "Pull your shoulders back and down and keep them there",
    "Bend your elbows to lift the weights toward your shoulders, palms still facing in",
    "Lower the weights slowly until your arms are straight",
    "Stay upright, do not arch your back or shrug your shoulders",
  ],
  "Incline Dumbbell Curl": [
    "Set a bench to about 45 to 60 degrees and sit back on it",
    "Let both arms hang straight down with palms facing in",
    "Keep your elbows back by your sides",
    "Curl the weight up, turning your palm to face your shoulder",
    "Lower it slowly back to the start",
    "Keep your upper arms still and your back against the bench",
  ],
  "Preacher Curl": [
    "Sit at the preacher bench with the back of your upper arms on the pad",
    "Adjust the seat so your armpits sit near the top of the pad",
    "Grab the bar with palms facing up, hands shoulder width apart",
    "Curl the bar up until your forearms point straight up",
    "Lower the bar slowly until your arms are fully straight",
    "Keep your upper arms pressed on the pad, never drop the weight fast",
  ],

  // Legs
  "Barbell Back Squat": [
    "Rest the bar across your upper back, hands wider than your shoulders",
    "Step back and stand with feet a little wider than shoulder width, chest up",
    "Push your hips back and bend your knees, like sitting into a chair",
    "Go down until your thighs are at least level with the floor, back straight",
    "Push through your whole foot and drive your hips forward to stand up",
    "Keep your knees pointing the same way as your toes, heels flat",
  ],
  "Leg Press": [
    "Sit with your back and hips flat against the pad",
    "Place both feet flat on the platform about shoulder width apart",
    "Release the safety handles and bend your knees slowly to lower the weight",
    "Stop before your hips lift or roll off the seat",
    "Push the platform back up until your legs are almost straight",
    "Keep your knees lined up with your toes, heels flat on the platform",
  ],
  "Walking Lunges": [
    "Stand tall with feet hip width apart",
    "Take a big step forward, landing heel first",
    "Bend both knees and lower your hips straight down, not forward",
    "Stop when your front thigh is level with the floor and your back knee is near the ground",
    "Push off your front foot and step straight into the next lunge",
    "Keep your chest up, drop your hips down instead of sliding your knee far past your toes",
  ],
  "Romanian Deadlift": [
    "Stand holding the bar at hip level, hands shoulder width apart",
    "Keep your back straight and chest up, then push your hips back",
    "Let the bar slide down close to your legs, knees bending only a little",
    "Stop when you feel a strong stretch in the back of your thighs",
    "Drive your hips forward and stand tall, arms staying straight",
    "Never let your lower back round, keep the bar close to your legs",
  ],
  "Leg Curl": [
    "Lie face down with the pad resting just above your heels",
    "Line your knees up just off the edge of the bench",
    "Hold the handles to keep your body steady",
    "Bend your knees and pull the pad up toward your glutes",
    "Pause at the top, then lower slowly until your legs are straight",
    "Keep your hips pressed down so your lower back does not arch",
  ],
  "Standing Calf Raise": [
    "Place the balls of your feet on the edge of the platform, heels hanging off",
    "Stand up tall with the weight on your shoulders, legs straight",
    "Push up onto your toes, lifting your heels as high as you can",
    "Pause at the top for a second",
    "Lower your heels slowly below the platform until you feel a stretch",
    "Move slowly without bouncing",
  ],

  // Core
  "Hanging Leg Raise": [
    "Grab a pull up bar with hands a bit wider than your shoulders",
    "Hang with arms straight and pull your shoulders down slightly",
    "Lift your legs together until they are at least level with your hips",
    "Bend your knees to make it easier",
    "Lower your legs slowly until they hang straight",
    "Move slowly without swinging so your muscles do the work, not momentum",
  ],
};
